
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core'
  inputs:
    version: 6.x
    includePreviewVersions: true
    
- task: DotNetCoreCLI@2
  displayName: 'Build - $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: 'SystemsInsight.RadarToolbox.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: |
     **/*Tests/*.csproj 
     !**/*Tests/*Rtsa*.csproj
     !**/*Tests/*DAL*.csproj
    arguments: '--configuration $(buildConfiguration)'